# SPDX-FileCopyrightText: 2026 Chili.CHIPS*ba
# 
# SPDX-License-Identifier: BSD-3-Clause

version = 1

[[annotations]]
path = ["0.doc/**", "4.build/csr_build/generated-files/html/**", "4.build/hw_build.openXC7/build_artifacts/**", "4.build/hw_build.openXC7/build_artifacts.switched/**", "4.build/hw_build.openXC7/converted/**", "4.build/hw_build.openXC7/converted.switched/**", "4.build/sw_build/**", "5.sim/**.gtkw", "5.sim/**.fst", "5.sim/**.ron", "5.sim/**.pcap"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Chili.CHIPS*ba"
SPDX-License-Identifier = "BSD-3-Clause"
