# SPDX-FileCopyrightText: 2026 Chili.CHIPS
#
# SPDX-License-Identifier: BSD-3-Clause

"""Write parameterised (* blackbox *) SystemVerilog stubs of Xilinx primitives,
for Yosys's SystemVerilog front end (read_slang, FRONTEND=slang in the Makefile).

read_slang elaborates the whole hierarchy up front, so every primitive must be
declared -- with its parameters, or every parameter the RTL sets is rejected.
Blackboxes loaded into Yosys with read_verilog -lib carry no parameters into
slang (povik/sv-elab#367 would change that), and Yosys's cells_sim.v does not
pass slang's checks (parameters in specify blocks). So the declarations are
taken from Yosys's own cells_xtra.v / cells_sim.v and reduced to header, ports
and parameters.

Two adjustments, both for upstream problems:
  * real-valued parameter defaults become strings -- sv-elab cannot pass a real
    to a primitive, not even an untouched default (povik/sv-elab#282). The RTL
    leaves its own real-valued settings out under `define SYN_YOSYS_BUG.
  * IBUFDS_GTE2.CLKSWING_CFG defaults to "TRUE" in cells_xtra.v; Xilinx's
    unisims say 2'b11, and nextpnr aborts on "TRUE" ("Expecting numeric value").

usage: python3 gen_xilinx_bb.py <yosys datdir>/xilinx <out.sv> PRIMITIVE [...]
"""

# FIXME: this whole script is a tool workaround (openPCIE #29); drop it once
# read_slang can take cells_sim.v or sv-elab#367 is merged.

import re
import sys

# Defaults that Yosys's cells_xtra.v gets wrong (Vivado unisims are the reference)
# FIXME: remove once Yosys fixes CLKSWING_CFG (openPCIE #19)
DEFAULT_FIXES = {("IBUFDS_GTE2", "CLKSWING_CFG"): "2'b11"}


def module_text(lib, name):
    m = re.search(rf"^module\s+{name}\b.*?^endmodule\b", lib, re.S | re.M)
    if not m:
        raise SystemExit(f"gen_xilinx_bb: {name} not found in the Yosys library")
    return m.group(0)


def stub(lib, name):
    t = module_text(lib, name)
    t = re.sub(r"\bspecify\b.*?\bendspecify\b", "", t, flags=re.S)
    t = re.sub(r"//[^\n]*", "", t)
    t = re.sub(r"/\*.*?\*/", "", t, flags=re.S)

    # The header ends at the ';' that closes the port list
    depth = 0
    for i, c in enumerate(t):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == ";" and depth == 0:
            break
    header = re.sub(r"\(\*.*?\*\)", "", t[: i + 1], flags=re.S)

    keep = []
    for stmt in re.findall(r"[^;]*;", t[i + 1 :]):
        s = " ".join(re.sub(r"\(\*.*?\*\)", "", stmt, flags=re.S).split())
        m = re.match(r"parameter\s+real\s+(\w+)\s*=\s*([-0-9.eE+]+)\s*;$", s)
        if m:
            s = f'parameter {m.group(1)} = "{m.group(2)}";'
        m = re.match(r"parameter\s+(?:\[[^\]]*\]\s*)?(\w+)\s*=", s)
        if m and (name, m.group(1)) in DEFAULT_FIXES:
            s = f"parameter {m.group(1)} = {DEFAULT_FIXES[(name, m.group(1))]};"
        if re.match(r"(parameter|input|output|inout)\b", s):
            keep.append("  " + s)

    return "(* blackbox *)\n" + header.strip() + "\n" + "\n".join(keep) + "\nendmodule\n"


def main():
    libdir, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    lib = ""
    for f in ("cells_xtra.v", "cells_sim.v"):
        with open(f"{libdir}/{f}") as fh:
            lib += fh.read() + "\n"
    with open(out, "w") as fh:
        fh.write("// Generated by gen_xilinx_bb.py from Yosys cells_xtra.v / cells_sim.v\n"
                 "// -- parameterised blackboxes for read_slang. Do not edit.\n\n")
        for n in names:
            fh.write(stub(lib, n) + "\n")
    print(f"OK -> {out} ({len(names)} blackboxes)")


if __name__ == "__main__":
    main()
