module pll_bank (
	QPLL_CPLLPDREFCLK,
	QPLL_GTGREFCLK,
	QPLL_QPLLLOCKDETCLK,
	QPLL_QPLLOUTCLK,
	QPLL_QPLLOUTREFCLK,
	QPLL_QPLLLOCK,
	QPLL_QPLLPD,
	QPLL_QPLLRESET,
	QPLL_DRPCLK,
	QPLL_DRPADDR,
	QPLL_DRPEN,
	QPLL_DRPDI,
	QPLL_DRPWE,
	QPLL_DRPDO,
	QPLL_DRPRDY
);
	localparam PCIE_GT_DEVICE = "GTP";
	localparam PCIE_USE_MODE = "1.0";
	localparam PCIE_PLL_SEL = "CPLL";
	localparam PCIE_REFCLK_FREQ = 0;
	input QPLL_CPLLPDREFCLK;
	input QPLL_GTGREFCLK;
	input QPLL_QPLLLOCKDETCLK;
	output wire QPLL_QPLLOUTCLK;
	output wire QPLL_QPLLOUTREFCLK;
	output wire QPLL_QPLLLOCK;
	input QPLL_QPLLPD;
	input QPLL_QPLLRESET;
	input QPLL_DRPCLK;
	input [7:0] QPLL_DRPADDR;
	input QPLL_DRPEN;
	input [15:0] QPLL_DRPDI;
	input QPLL_DRPWE;
	output wire [15:0] QPLL_DRPDO;
	output wire QPLL_DRPRDY;
	localparam GTP_QPLL_FBDIV = 3'd5;
	localparam BIAS_CFG = 64'h0000042000001000;
	wire cpllpd;
	wire cpllrst;
	generate
		if (PCIE_GT_DEVICE == "GTP") begin : hm_cmn
			GTPE2_COMMON #(
				.SIM_PLL0REFCLK_SEL(3'b001),
				.SIM_PLL1REFCLK_SEL(3'b001),
				.SIM_RESET_SPEEDUP("FALSE"),
				.SIM_VERSION(PCIE_USE_MODE),
				.PLL0_CFG(27'h01f024c),
				.PLL1_CFG(27'h01f024c),
				.PLL_CLKOUT_CFG(8'd0),
				.PLL0_DMON_CFG(1'b0),
				.PLL1_DMON_CFG(1'b0),
				.PLL0_FBDIV(GTP_QPLL_FBDIV),
				.PLL1_FBDIV(GTP_QPLL_FBDIV),
				.PLL0_FBDIV_45(5),
				.PLL1_FBDIV_45(5),
				.PLL0_INIT_CFG(24'h00001e),
				.PLL1_INIT_CFG(24'h00001e),
				.PLL0_LOCK_CFG(9'h1e8),
				.PLL1_LOCK_CFG(9'h1e8),
				.PLL0_REFCLK_DIV(1),
				.PLL1_REFCLK_DIV(1),
				.BIAS_CFG(64'h0000000000050001),
				.RSVD_ATTR0(16'd0),
				.RSVD_ATTR1(16'd0)
			) gtpe2_common_i(
				.GTGREFCLK0(),
				.GTGREFCLK1(),
				.GTREFCLK0(QPLL_GTGREFCLK),
				.GTREFCLK1(),
				.GTEASTREFCLK0(),
				.GTEASTREFCLK1(),
				.GTWESTREFCLK0(),
				.GTWESTREFCLK1(),
				.PLL0LOCKDETCLK(QPLL_QPLLLOCKDETCLK),
				.PLL1LOCKDETCLK(QPLL_QPLLLOCKDETCLK),
				.PLL0LOCKEN(1'd1),
				.PLL1LOCKEN(1'd1),
				.PLL0REFCLKSEL(3'd1),
				.PLL1REFCLKSEL(3'd1),
				.PLLRSVD1(16'd0),
				.PLLRSVD2(5'd0),
				.PLL0OUTCLK(QPLL_QPLLOUTCLK),
				.PLL1OUTCLK(),
				.PLL0OUTREFCLK(QPLL_QPLLOUTREFCLK),
				.PLL1OUTREFCLK(),
				.PLL0LOCK(QPLL_QPLLLOCK),
				.PLL1LOCK(),
				.PLL0FBCLKLOST(),
				.PLL1FBCLKLOST(),
				.PLL0REFCLKLOST(),
				.PLL1REFCLKLOST(),
				.DMONITOROUT(),
				.PLL0PD(cpllpd | QPLL_QPLLPD),
				.PLL1PD(1'd1),
				.PLL0RESET(cpllrst | QPLL_QPLLRESET),
				.PLL1RESET(1'd1),
				.DRPCLK(QPLL_DRPCLK),
				.DRPADDR(QPLL_DRPADDR),
				.DRPEN(QPLL_DRPEN),
				.DRPDI(QPLL_DRPDI),
				.DRPWE(QPLL_DRPWE),
				.DRPDO(QPLL_DRPDO),
				.DRPRDY(QPLL_DRPRDY),
				.BGBYPASSB(1'd1),
				.BGMONITORENB(1'd1),
				.BGPDB(1'd1),
				.BGRCALOVRD(5'd31),
				.BGRCALOVRDENB(1'd1),
				.PMARSVD(8'd0),
				.RCALENB(1'd1),
				.REFCLKOUTMONITOR0(),
				.REFCLKOUTMONITOR1(),
				.PMARSVDOUT()
			);
		end
	endgenerate
	wake_timer wake_timer_i(
		.i_ibufds_gte2(QPLL_CPLLPDREFCLK),
		.o_cpllpd_ovrd(cpllpd),
		.o_cpllreset_ovrd(cpllrst)
	);
endmodule
