// SPDX-FileCopyrightText: 2026 Chili.CHIPS
//
// SPDX-License-Identifier: BSD-3-Clause

//==========================================================================
// openPCIE * NLnet-sponsored open-source implementation
//--------------------------------------------------------------------------
//                   Copyright (C) 2026 Chili.CHIPS
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
// contributors may be used to endorse or promote products derived
// from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
// IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//              https://opensource.org/license/bsd-3-clause
//--------------------------------------------------------------------------
// Description:
//   opensource openPCIE software FSM that replaces AMD-proprietary RTL FSM
//   Switched topology: ASM1184e PCIe switch with up to 4 endpoints behind it
//
//   Bus map produced by this firmware (same as the AMD cgator_cfg_rom.data):
//
//     bus 0 .............. Root Complex
//      |
//     bus 1  dev 0 ....... ASM1184e upstream port      (pri 1, sec 2, sub 6)
//      |
//     bus 2  dev 1 ....... downstream port 1 --> bus 3, window 0x10000000
//            dev 3 ....... downstream port 2 --> bus 4, window 0x10100000
//            dev 5 ....... downstream port 3 --> bus 5, window 0x10200000
//            dev 7 ....... downstream port 4 --> bus 6, window 0x10300000
//      |
//     bus 3..6  dev 0 .... the endpoint cards, BAR0 at the window base
//
//   Everything on bus 1 is reached with Type 0 Configuration TLPs, everything
//   deeper with Type 1. That selection is NOT made here -- riscv_pcie_soc.sv
//   derives it from the bus number in TX_HEADER2, which is the one RTL
//   difference between this build and RC-direct.
//==========================================================================

#include <stdint.h>

// -------------------------------------------------------------------------
// CSR access -- two interchangeable back-ends, exactly as in the RTL
//
//   (no define)          : the hand-written register map, hard-coded here
//   -DUSE_PEAKRDL_CSR    : the map generated by PeakRDL out of
//                          4.build/csr_build/csr.rdl. Register offsets and
//                          field positions then come from the generated
//                          header instead of from the constants below, so
//                          hardware and software can never drift apart.
//
// 4.build/sw_build passes -DUSE_PEAKRDL_CSR by default (CSR = peakrdl in
// 4.build/config.mk); build the hand-written one with:  make CSR=legacy
// -------------------------------------------------------------------------
#ifdef USE_PEAKRDL_CSR

#include "openpcie_regs.h"

#define PCIE_TX_HEADER0      CSR_REG32(tx.header0)
#define PCIE_TX_HEADER1      CSR_REG32(tx.header1)
#define PCIE_TX_HEADER2      CSR_REG32(tx.header2)
#define PCIE_TX_DATA         CSR_REG32(tx.data)

#define PCIE_RX_STATUS       CSR_REG32(rx.status)
#define PCIE_RX_DATA         CSR_REG32(rx.data)
#define PCIE_RX_HEADER_INFO  CSR_REG32(rx.header_info)
#define PCIE_ERR_STATUS      CSR_REG32(status.err)
#define PCIE_PHY_STATUS      CSR_REG32(status.phy)

// Field masks and positions come from the generated csr.h, via RDL_FIELD()
#define TX_STATE_MASK        CSR__STATUS__PHY__TX_STATE_bm
#define TX_BUF_MASK          CSR__STATUS__PHY__TX_BUF_AV_bm

#define RX_REQUESTER_ID(hdr) RDL_FIELD(hdr, CSR__RX__HEADER_INFO__REQUESTER_ID)
#define RX_TAG(hdr)          RDL_FIELD(hdr, CSR__RX__HEADER_INFO__TAG)

#else

#define PCIE_TX_HEADER0      (*(volatile uint32_t*)(0x30000000))
#define PCIE_TX_HEADER1      (*(volatile uint32_t*)(0x30000004))
#define PCIE_TX_HEADER2      (*(volatile uint32_t*)(0x30000008))
#define PCIE_TX_DATA         (*(volatile uint32_t*)(0x3000000C))

#define PCIE_RX_STATUS       (*(volatile uint32_t*)(0x30000010))
#define PCIE_RX_DATA         (*(volatile uint32_t*)(0x30000014))
#define PCIE_RX_HEADER_INFO  (*(volatile uint32_t*)(0x30000018))
#define PCIE_ERR_STATUS      (*(volatile uint32_t*)(0x3000001C))
#define PCIE_PHY_STATUS      (*(volatile uint32_t*)(0x30000020))

#define TX_STATE_MASK        0xC0
#define TX_BUF_MASK          0x3F

#define RX_REQUESTER_ID(hdr) (((hdr) >> 16) & 0xFFFF)
#define RX_TAG(hdr)          (((hdr) >>  8) & 0xFF)

#endif
#define MY_REQUESTER_ID  0x10EE

#define TLP_CFG_WR0 0x44000000
#define TLP_CFG_RD0 0x04000000
#define TLP_MEM_WR  0x40000000
#define TLP_MEM_RD  0x00000000

#define CPL_STAT_SC  0 // Successful
#define CPL_STAT_UR  1 // Unsupported Request
#define CPL_STAT_CRS 2 // Configuration Retry Status (Busy)
#define CPL_STAT_CA  4 // Completer Abort
#define CPL_TIMEOUT  8 // not a PCIe status: no Completion arrived in time

#define CPL_POLL_LIMIT 2000000 // polls of rx.header_info before giving up
#define CRS_RETRIES    100     // re-issues of a request answered with CRS

// Configuration space offsets used below
#define CFG_ID           0x00 // Device ID / Vendor ID
#define CFG_COMMAND      0x04
#define CFG_BAR0         0x10
#define CFG_BUS_NUMBERS  0x18 // primary / secondary / subordinate
#define CFG_MEM_LIMITS   0x20 // memory base and limit of the bridge window
#define NUM_BARS         6

#define CMD_MEM_BUS_MASTER 0x00000006 // Memory Space Enable + Bus Master Enable

// Topology, exactly as laid out in the AMD configuration ROM
#define SWITCH_BUS        1
#define SWITCH_INTERNAL   2
#define SWITCH_SUBORD     6
#define NUM_PORTS         4

#define WINDOW_BASE       0x10000000
#define WINDOW_SIZE       0x00100000

// Result markers written to PCIE_TX_DATA
#define RESULT_PASS        0x0000FACE // every endpoint that was found passed
#define RESULT_FAIL        0x0000DEAD // an endpoint failed its memory readback
#define RESULT_NO_SWITCH   0xBAD00000 // the switch upstream port did not answer
#define RESULT_NO_DEVICE   0xBAD00001 // switch is up but no endpoint was found
#define RESULT_CFG_FAILED  0xBAD00002 // a config request to a found device failed
#define RESULT_BAR0_FAILED 0xBAD00003 // an endpoint BAR0 is missing, I/O, or
                                      // larger than its 1 MB port window

// Downstream port device numbers and the bus number handed to each of them
static const uint8_t port_dev[NUM_PORTS] = { 1, 3, 5, 7 };
static const uint8_t port_bus[NUM_PORTS] = { 3, 4, 5, 6 };

// Cycles to idle at start-up, waiting for the PCIe link to finish training.
// On hardware that wait is unavoidable. In co-simulation the link is already up
// by the time the SOC leaves reset, and this loop -- compiled without
// optimisation -- costs about 80 ms of simulated time, so the simulation build
// shortens it:  make SIM=1  in 4.build/sw_build.
#ifndef STARTUP_DELAY
#define STARTUP_DELAY 100000
#endif

uint8_t tx_tag;

void wait_cycles(int n) {
    for (int i = 0; i < n; i++) __asm__("nop");
}

__attribute__((noreturn)) void halt(uint32_t marker) {
    PCIE_TX_DATA = marker;
    while (1) {}
}

void send_tlp(uint32_t h0, uint32_t h1, uint32_t h2, uint32_t data) {
    while (((PCIE_PHY_STATUS & TX_STATE_MASK) != 0) ||
           ((PCIE_PHY_STATUS & TX_BUF_MASK) == 0));

    PCIE_TX_HEADER0 = h0;
    PCIE_TX_HEADER1 = h1;
    PCIE_TX_HEADER2 = h2;
    PCIE_TX_DATA = data;
}

// Waits for the Completion carrying `tag` and returns its Completion Status
// (CPL_STAT_*), or CPL_TIMEOUT. The payload is stored to *data only on SC, so
// a genuine 0xFFFFFFFF read can no longer be mistaken for an error.
uint32_t wait_for_completion(uint8_t tag, uint32_t *data) {
    volatile int timeout = CPL_POLL_LIMIT;

    while (timeout > 0) {
        uint32_t raw_header = PCIE_RX_HEADER_INFO;
        uint16_t rx_req_id = RX_REQUESTER_ID(raw_header);
        uint8_t  rx_tag    = RX_TAG(raw_header);

        if (rx_req_id == MY_REQUESTER_ID && rx_tag == tag) {
            uint32_t rx_status = PCIE_RX_STATUS;

            if (rx_status == CPL_STAT_SC && data) {
                *data = PCIE_RX_DATA;
            }
            return rx_status;
        }
        timeout--;
    }
    return CPL_TIMEOUT;
}

// Sends one non-posted request and waits for its Completion. A device that is
// still initialising may answer a Configuration Request -- read or write --
// with CRS; the request is then re-issued, with a fresh tag, up to CRS_RETRIES
// times. Returns the final Completion Status.
uint32_t pcie_request(uint32_t type, uint32_t addr_or_id, uint32_t wdata, uint32_t *rdata) {
    uint32_t status = CPL_TIMEOUT;

    for (int retry_count = 0; retry_count <= CRS_RETRIES; retry_count++) {

        uint8_t current_tag = tx_tag++;

        send_tlp(type | 0x01,
                 (MY_REQUESTER_ID << 16) | (current_tag << 8) | 0x0F,
                 addr_or_id & 0xFFFFFFFC,
                 wdata);

        status = wait_for_completion(current_tag, rdata);

        if (status != CPL_STAT_CRS) {
            break;
        }
        wait_cycles(1000);
    }
    return status;
}

uint32_t pcie_cfg_write(uint32_t bus, uint32_t dev, uint32_t func, uint32_t reg, uint32_t val) {
    uint32_t id = (bus << 24) | (dev << 19) | (func << 16) | (reg & 0xFC);
    return pcie_request(TLP_CFG_WR0, id, val, 0);
}

uint32_t pcie_cfg_read(uint32_t bus, uint32_t dev, uint32_t func, uint32_t reg, uint32_t *val) {
    uint32_t id = (bus << 24) | (dev << 19) | (func << 16) | (reg & 0xFC);
    return pcie_request(TLP_CFG_RD0, id, 0, val);
}

void pcie_mem_write(uint32_t addr, uint32_t val) {
	uint8_t tag = tx_tag++;

    // Posted -- no Completion to wait for
    send_tlp(TLP_MEM_WR | 0x01,
             (MY_REQUESTER_ID << 16) | (tag << 8) | 0x0F,
             addr & 0xFFFFFFFC,
             val);
}

uint32_t pcie_mem_read(uint32_t addr, uint32_t *val) {
    return pcie_request(TLP_MEM_RD, addr, 0, val);
}

//--------------------------------------------------------------------------
// Configuration space payloads travel big-endian: byte 0 of the register ends
// up in bits [31:24] of the data dword. The two helpers below swap on the way
// in and out, so every value in this file is written the way the spec prints
// it (BAR 0x80000000, not 0x00000080).
//
// cfg_write32() is the checked write: any status other than SC stops the
// firmware with RESULT_CFG_FAILED.
//--------------------------------------------------------------------------
static uint32_t bswap32(uint32_t v) {
    return ((v & 0x000000FFu) << 24) |
           ((v & 0x0000FF00u) <<  8) |
           ((v & 0x00FF0000u) >>  8) |
           ((v & 0xFF000000u) >> 24);
}

static void cfg_write32(uint32_t bus, uint32_t dev, uint32_t reg, uint32_t val) {
    if (pcie_cfg_write(bus, dev, 0, reg, bswap32(val)) != CPL_STAT_SC) {
        halt(RESULT_CFG_FAILED);
    }
}

static uint32_t cfg_read32(uint32_t bus, uint32_t dev, uint32_t reg, uint32_t *val) {
    uint32_t raw;
    uint32_t status = pcie_cfg_read(bus, dev, 0, reg, &raw);

    if (status == CPL_STAT_SC) {
        *val = bswap32(raw);
    }
    return status;
}

// The checked read, for a device already known to be there
static uint32_t cfg_read32_checked(uint32_t bus, uint32_t dev, uint32_t reg) {
    uint32_t val;

    if (cfg_read32(bus, dev, reg, &val) != CPL_STAT_SC) {
        halt(RESULT_CFG_FAILED);
    }
    return val;
}

//--------------------------------------------------------------------------
// BAR sizing and assignment. For each of the six BARs:
//   - write all ones, read back; 0 means the BAR is not implemented
//   - bit 0 set: I/O BAR. This RC has no I/O space -- left unassigned
//   - bits [2:1] = 10: 64-bit BAR, the next BAR holds the upper half
//   - size = ~(readback & ~0xF) + 1, the base is aligned to it
// BARs are packed into [win_base, win_base + win_size) in order. One that does
// not fit is not squeezed in but parked out of the way: a 64-bit BAR above
// 4 GB (out of reach of the 3-DW requests this RC sends), a 32-bit one at 0,
// below every window. Only BAR0 is used by the self-test.
//
// Memory decoding is switched off while the BARs move.
// Returns the address given to BAR0, or 0 when BAR0 could not be placed.
//--------------------------------------------------------------------------
static uint32_t assign_bars(uint32_t bus, uint32_t dev,
                            uint32_t win_base, uint32_t win_size) {
    uint32_t next     = 0; // first free offset inside the window
    uint32_t bar0     = 0;

    cfg_write32(bus, dev, CFG_COMMAND, 0);

    for (int i = 0; i < NUM_BARS; i++) {
        uint32_t reg = CFG_BAR0 + 4 * i;

        cfg_write32(bus, dev, reg, 0xFFFFFFFF);
        uint32_t lo = cfg_read32_checked(bus, dev, reg);

        if (lo == 0) {
            continue;                             // not implemented
        }
        if (lo & 0x1) {
            cfg_write32(bus, dev, reg, 0);        // I/O -- left unassigned
            continue;
        }

        int      is64 = (((lo >> 1) & 0x3) == 0x2) && (i < NUM_BARS - 1);
        uint32_t hi   = 0xFFFFFFFF;               // upper half of the size mask

        if (is64) {
            cfg_write32(bus, dev, reg + 4, 0xFFFFFFFF);
            hi = cfg_read32_checked(bus, dev, reg + 4);
        }

        uint32_t size = ~(lo & 0xFFFFFFF0) + 1;   // 0 when 4 GB or more
        int      fits = 0;
        uint32_t base = 0;

        if (hi == 0xFFFFFFFF && size != 0 && size <= win_size) {
            base = (next + size - 1) & ~(size - 1);
            fits = (base <= win_size - size);
        }

        if (fits) {
            cfg_write32(bus, dev, reg, win_base + base);
            if (is64) {
                cfg_write32(bus, dev, reg + 4, 0);
            }
            next = base + size;
            if (i == 0) {
                bar0 = win_base + base;
            }
        } else if (is64) {
            // Base = size (aligned to itself), but never below 4 GB
            uint32_t park_hi = (hi == 0xFFFFFFFF) ? 1 : ~hi + 1;
            cfg_write32(bus, dev, reg, 0);
            cfg_write32(bus, dev, reg + 4, park_hi);
        } else {
            cfg_write32(bus, dev, reg, 0);
        }

        if (is64) {
            i++;                                  // upper half done
        }
    }
    return bar0;
}

// A device is there when it answers the ID read with SC. Behind a switch an
// empty slot is answered with UR by the downstream port.
static int device_present(uint32_t bus, uint32_t dev) {
    uint32_t id;

    if (cfg_read32(bus, dev, CFG_ID, &id) != CPL_STAT_SC) {
        return 0;
    }
    return (id != 0xFFFFFFFF) && (id != 0x00000000);
}

//--------------------------------------------------------------------------
// Bridge (Type 1) header helpers
//--------------------------------------------------------------------------

// Register 0x18: byte 0 = primary, byte 1 = secondary, byte 2 = subordinate
static void bridge_set_buses(uint32_t bus, uint32_t dev,
                             uint8_t primary, uint8_t secondary, uint8_t subordinate) {
    cfg_write32(bus, dev, CFG_BUS_NUMBERS,
                ((uint32_t)subordinate << 16) |
                ((uint32_t)secondary   <<  8) |
                ((uint32_t)primary));
}

// Register 0x20: [15:0] memory base, [31:16] memory limit. In both halves it is
// bits [15:4] that carry address bits [31:20], so the window granularity is
// 1 MB and the low nibble is read-only. The limit is inclusive -- it names the
// last megabyte still inside the window, not the first one outside it.
static void bridge_set_window(uint32_t bus, uint32_t dev,
                              uint32_t base, uint32_t size) {
    uint32_t base_field  = (base >> 16) & 0xFFF0;
    uint32_t limit_field = ((base + size - 1) >> 16) & 0xFFF0;

    cfg_write32(bus, dev, CFG_MEM_LIMITS, (limit_field << 16) | base_field);
}

int main() {

    tx_tag = 0;

    wait_cycles(STARTUP_DELAY);

    //----------------------------------------------------------------------
    // STEP 1: switch upstream port -- bus 1, device 0
    // Reached with Type 0 requests; it captures bus number 1 from them.
    //----------------------------------------------------------------------
    if (!device_present(SWITCH_BUS, 0)) {
        halt(RESULT_NO_SWITCH);
    }

    // Primary 1 (link towards the RC), secondary 2 (internal bus),
    // subordinate 6 (highest bus number behind this port)
    bridge_set_buses(SWITCH_BUS, 0, SWITCH_BUS, SWITCH_INTERNAL, SWITCH_SUBORD);

    // One window covering all four downstream windows: 0x10000000 - 0x103FFFFF
    bridge_set_window(SWITCH_BUS, 0, WINDOW_BASE, NUM_PORTS * WINDOW_SIZE);

    cfg_write32(SWITCH_BUS, 0, CFG_COMMAND, CMD_MEM_BUS_MASTER);

    //----------------------------------------------------------------------
    // STEP 2: the four downstream ports on the internal bus 2
    // Each is a virtual PCI-to-PCI bridge and gets its own secondary bus and
    // its own 1 MB memory window carved out of the upstream window.
    //----------------------------------------------------------------------
    for (int p = 0; p < NUM_PORTS; p++) {
        uint32_t base = WINDOW_BASE + (uint32_t)p * WINDOW_SIZE;

        bridge_set_buses(SWITCH_INTERNAL, port_dev[p],
                         SWITCH_INTERNAL, port_bus[p], port_bus[p]);

        bridge_set_window(SWITCH_INTERNAL, port_dev[p], base, WINDOW_SIZE);

        cfg_write32(SWITCH_INTERNAL, port_dev[p], CFG_COMMAND, CMD_MEM_BUS_MASTER);
    }

    //----------------------------------------------------------------------
    // STEP 3: the endpoint cards, one per downstream port, always device 0 on
    // the secondary bus of that port. Slots may be empty, so each one is
    // probed first and silently skipped when there is no answer.
    //----------------------------------------------------------------------
    uint32_t ep_bar0[NUM_PORTS]; // 0 = slot empty
    int      found = 0;

    for (int p = 0; p < NUM_PORTS; p++) {
        uint32_t base = WINDOW_BASE + (uint32_t)p * WINDOW_SIZE;

        ep_bar0[p] = 0;
        if (!device_present(port_bus[p], 0)) {
            continue;
        }

        // The BARs have to land inside the window the port forwards, otherwise
        // the downstream port drops every memory request aimed at them.
        ep_bar0[p] = assign_bars(port_bus[p], 0, base, WINDOW_SIZE);
        if (ep_bar0[p] == 0) {
            halt(RESULT_BAR0_FAILED);
        }

        cfg_write32(port_bus[p], 0, CFG_COMMAND, CMD_MEM_BUS_MASTER);

        found++;
    }

    if (found == 0) {
        halt(RESULT_NO_DEVICE);
    }

    //----------------------------------------------------------------------
    // STEP 4: memory write / readback through the switch, one endpoint at a
    // time. This is the same self-test the direct build runs, repeated for
    // every populated slot.
    //----------------------------------------------------------------------
    uint32_t test_data = 0x00000006;
    int      failures  = 0;

    for (int p = 0; p < NUM_PORTS; p++) {
        uint32_t readback;

        if (ep_bar0[p] == 0) {
            continue;
        }

        pcie_mem_write(ep_bar0[p], test_data);

        if (pcie_mem_read(ep_bar0[p], &readback) != CPL_STAT_SC ||
            readback != test_data) {
            failures++;
        }
    }

    if (failures == 0) {
        halt(RESULT_PASS);
    } else {
        halt(RESULT_FAIL);
    }
}

//--------------------------------------------------------------------------
// Revision history:
//  2026/07/31 AV - initial creation, derived from the RC-direct firmware
//  2026/10/06    - Completion Status checked on every request (CRS retry on
//                  config writes too), real BAR sizing inside the port window
//--------------------------------------------------------------------------
