// SPDX-FileCopyrightText: 2026 Chili.CHIPS*ba
//
// SPDX-License-Identifier: BSD-3-Clause

// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef CSR_H
#define CSR_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// mem - openpcie::imem
typedef struct __attribute__ ((__packed__)) {
    uint32_t mem[2048];
} openpcie__imem_t;

// reg - csr::tx::header0
#define CSR__TX__HEADER0__HDR_bm 0xffffffff
#define CSR__TX__HEADER0__HDR_bp 0
#define CSR__TX__HEADER0__HDR_bw 32
#define CSR__TX__HEADER0__HDR_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t hdr :32;
    } f;
    uint32_t w;
} csr__tx__header0_t;

// reg - csr::tx::header1
#define CSR__TX__HEADER1__HDR_bm 0xffffffff
#define CSR__TX__HEADER1__HDR_bp 0
#define CSR__TX__HEADER1__HDR_bw 32
#define CSR__TX__HEADER1__HDR_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t hdr :32;
    } f;
    uint32_t w;
} csr__tx__header1_t;

// reg - csr::tx::header2
#define CSR__TX__HEADER2__HDR_bm 0xffffffff
#define CSR__TX__HEADER2__HDR_bp 0
#define CSR__TX__HEADER2__HDR_bw 32
#define CSR__TX__HEADER2__HDR_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t hdr :32;
    } f;
    uint32_t w;
} csr__tx__header2_t;

// reg - csr::tx::data
#define CSR__TX__DATA__PAYLOAD_bm 0xffffffff
#define CSR__TX__DATA__PAYLOAD_bp 0
#define CSR__TX__DATA__PAYLOAD_bw 32
#define CSR__TX__DATA__PAYLOAD_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t payload :32;
    } f;
    uint32_t w;
} csr__tx__data_t;

// regfile - csr::tx
typedef struct __attribute__ ((__packed__)) {
    csr__tx__header0_t header0;
    csr__tx__header1_t header1;
    csr__tx__header2_t header2;
    csr__tx__data_t data;
} csr__tx_t;

// reg - csr::rx::status
#define CSR__RX__STATUS__CPL_STATUS_bm 0x7
#define CSR__RX__STATUS__CPL_STATUS_bp 0
#define CSR__RX__STATUS__CPL_STATUS_bw 3
#define CSR__RX__STATUS__CPL_STATUS_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t cpl_status :3;
        uint32_t :29;
    } f;
    uint32_t w;
} csr__rx__status_t;

// reg - csr::rx::data
#define CSR__RX__DATA__PAYLOAD_bm 0xffffffff
#define CSR__RX__DATA__PAYLOAD_bp 0
#define CSR__RX__DATA__PAYLOAD_bw 32
#define CSR__RX__DATA__PAYLOAD_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t payload :32;
    } f;
    uint32_t w;
} csr__rx__data_t;

// reg - csr::rx::header_info
#define CSR__RX__HEADER_INFO__LOWER_ADDR_bm 0x7f
#define CSR__RX__HEADER_INFO__LOWER_ADDR_bp 0
#define CSR__RX__HEADER_INFO__LOWER_ADDR_bw 7
#define CSR__RX__HEADER_INFO__LOWER_ADDR_reset 0x0
#define CSR__RX__HEADER_INFO__TAG_bm 0xff00
#define CSR__RX__HEADER_INFO__TAG_bp 8
#define CSR__RX__HEADER_INFO__TAG_bw 8
#define CSR__RX__HEADER_INFO__TAG_reset 0x0
#define CSR__RX__HEADER_INFO__REQUESTER_ID_bm 0xffff0000
#define CSR__RX__HEADER_INFO__REQUESTER_ID_bp 16
#define CSR__RX__HEADER_INFO__REQUESTER_ID_bw 16
#define CSR__RX__HEADER_INFO__REQUESTER_ID_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t lower_addr :7;
        uint32_t :1;
        uint32_t tag :8;
        uint32_t requester_id :16;
    } f;
    uint32_t w;
} csr__rx__header_info_t;

// regfile - csr::rx
typedef struct __attribute__ ((__packed__)) {
    csr__rx__status_t status;
    csr__rx__data_t data;
    csr__rx__header_info_t header_info;
} csr__rx_t;

// reg - csr::status::err
#define CSR__STATUS__ERR__CFG_STATUS_bm 0xffff
#define CSR__STATUS__ERR__CFG_STATUS_bp 0
#define CSR__STATUS__ERR__CFG_STATUS_bw 16
#define CSR__STATUS__ERR__CFG_STATUS_reset 0x0
#define CSR__STATUS__ERR__MSG_ERR_FATAL_bm 0x10000
#define CSR__STATUS__ERR__MSG_ERR_FATAL_bp 16
#define CSR__STATUS__ERR__MSG_ERR_FATAL_bw 1
#define CSR__STATUS__ERR__MSG_ERR_FATAL_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t cfg_status :16;
        uint32_t msg_err_fatal :1;
        uint32_t :15;
    } f;
    uint32_t w;
} csr__status__err_t;

// reg - csr::status::phy
#define CSR__STATUS__PHY__TX_BUF_AV_bm 0x3f
#define CSR__STATUS__PHY__TX_BUF_AV_bp 0
#define CSR__STATUS__PHY__TX_BUF_AV_bw 6
#define CSR__STATUS__PHY__TX_BUF_AV_reset 0x0
#define CSR__STATUS__PHY__TX_STATE_bm 0xc0
#define CSR__STATUS__PHY__TX_STATE_bp 6
#define CSR__STATUS__PHY__TX_STATE_bw 2
#define CSR__STATUS__PHY__TX_STATE_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t tx_buf_av :6;
        uint32_t tx_state :2;
        uint32_t :24;
    } f;
    uint32_t w;
} csr__status__phy_t;

// regfile - csr::status
typedef struct __attribute__ ((__packed__)) {
    csr__status__err_t err;
    csr__status__phy_t phy;
} csr__status_t;

// addrmap - csr
typedef struct __attribute__ ((__packed__)) {
    csr__tx_t tx;
    csr__rx_t rx;
    csr__status_t status;
} csr_t;

// addrmap - openpcie
typedef struct __attribute__ ((__packed__)) {
    openpcie__imem_t imem;
    uint8_t RESERVED_2000_2fffffff[0x2fffe000];
    csr_t csr;
} openpcie_t;


static_assert(sizeof(openpcie_t) == 0x30000024, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* CSR_H */
