// SPDX-FileCopyrightText: 2026 Chili.CHIPS*ba
//
// SPDX-License-Identifier: BSD-3-Clause

// ----------------------------------------------------------------------
// Auto-generated by sysrdl_cosim. *** DO NOT EDIT! ***
// Common openPCIE HAL header for both platform and co-simulation
//
// Copyright (C) 2026 Chili.CHIPS*ba
//
// ----------------------------------------------------------------------

#ifndef _CSR_BUILD_GENERATED_FILES_CSR_HW_H_ 
#define _CSR_BUILD_GENERATED_FILES_CSR_HW_H_

#include "csr.h"

#define PCIEMAIN        main

// -----------------------------------------------------
class imem_vp_t {
public:

    imem_vp_t(uint32_t* base_addr = (uint32_t*)0x0)
    {
    };

} ;

// -----------------------------------------------------
//
class csr__tx__header0_vp_t {
public:
    csr__tx__header0_vp_t (uint32_t* reg_addr = 0) : reg((csr__tx__header0_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     hdr(const uint32_t data) {reg->f.hdr = data;};
    inline uint32_t hdr()                    {return reg->f.hdr;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__tx__header0_t* reg;
};

// -----------------------------------------------------
//
class csr__tx__header1_vp_t {
public:
    csr__tx__header1_vp_t (uint32_t* reg_addr = 0) : reg((csr__tx__header1_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     hdr(const uint32_t data) {reg->f.hdr = data;};
    inline uint32_t hdr()                    {return reg->f.hdr;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__tx__header1_t* reg;
};

// -----------------------------------------------------
//
class csr__tx__header2_vp_t {
public:
    csr__tx__header2_vp_t (uint32_t* reg_addr = 0) : reg((csr__tx__header2_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     hdr(const uint32_t data) {reg->f.hdr = data;};
    inline uint32_t hdr()                    {return reg->f.hdr;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__tx__header2_t* reg;
};

// -----------------------------------------------------
//
class csr__tx__data_vp_t {
public:
    csr__tx__data_vp_t (uint32_t* reg_addr = 0) : reg((csr__tx__data_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     payload(const uint32_t data) {reg->f.payload = data;};
    inline uint32_t payload()                    {return reg->f.payload;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__tx__data_t* reg;
};

// -----------------------------------------------------
class csr__tx_vp_t {
public:

    csr__tx_vp_t(uint32_t* base_addr)
    {
        header0 = new csr__tx__header0_vp_t (base_addr + 0x0/4);
        header1 = new csr__tx__header1_vp_t (base_addr + 0x4/4);
        header2 = new csr__tx__header2_vp_t (base_addr + 0x8/4);
        data = new csr__tx__data_vp_t (base_addr + 0xc/4);
    };

    csr__tx__header0_vp_t* header0;
    csr__tx__header1_vp_t* header1;
    csr__tx__header2_vp_t* header2;
    csr__tx__data_vp_t* data;
} ;

// -----------------------------------------------------
//
class csr__rx__status_vp_t {
public:
    csr__rx__status_vp_t (uint32_t* reg_addr = 0) : reg((csr__rx__status_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     cpl_status(const uint32_t data) {reg->f.cpl_status = data;};
    inline uint32_t cpl_status()                    {return reg->f.cpl_status;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__rx__status_t* reg;
};

// -----------------------------------------------------
//
class csr__rx__data_vp_t {
public:
    csr__rx__data_vp_t (uint32_t* reg_addr = 0) : reg((csr__rx__data_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     payload(const uint32_t data) {reg->f.payload = data;};
    inline uint32_t payload()                    {return reg->f.payload;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__rx__data_t* reg;
};

// -----------------------------------------------------
//
class csr__rx__header_info_vp_t {
public:
    csr__rx__header_info_vp_t (uint32_t* reg_addr = 0) : reg((csr__rx__header_info_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     lower_addr(const uint32_t data) {reg->f.lower_addr = data;};
    inline uint32_t lower_addr()                    {return reg->f.lower_addr;};
    inline void     tag(const uint32_t data) {reg->f.tag = data;};
    inline uint32_t tag()                    {return reg->f.tag;};
    inline void     requester_id(const uint32_t data) {reg->f.requester_id = data;};
    inline uint32_t requester_id()                    {return reg->f.requester_id;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__rx__header_info_t* reg;
};

// -----------------------------------------------------
class csr__rx_vp_t {
public:

    csr__rx_vp_t(uint32_t* base_addr)
    {
        status = new csr__rx__status_vp_t (base_addr + 0x0/4);
        data = new csr__rx__data_vp_t (base_addr + 0x4/4);
        header_info = new csr__rx__header_info_vp_t (base_addr + 0x8/4);
    };

    csr__rx__status_vp_t* status;
    csr__rx__data_vp_t* data;
    csr__rx__header_info_vp_t* header_info;
} ;

// -----------------------------------------------------
//
class csr__status__err_vp_t {
public:
    csr__status__err_vp_t (uint32_t* reg_addr = 0) : reg((csr__status__err_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     cfg_status(const uint32_t data) {reg->f.cfg_status = data;};
    inline uint32_t cfg_status()                    {return reg->f.cfg_status;};
    inline void     msg_err_fatal(const uint32_t data) {reg->f.msg_err_fatal = data;};
    inline uint32_t msg_err_fatal()                    {return reg->f.msg_err_fatal;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__status__err_t* reg;
};

// -----------------------------------------------------
//
class csr__status__phy_vp_t {
public:
    csr__status__phy_vp_t (uint32_t* reg_addr = 0) : reg((csr__status__phy_t*)reg_addr) {};

    inline void     full(const uint32_t data) {reg->w = data;};
    inline uint32_t full()                    {return reg->w;};

    inline void     tx_buf_av(const uint32_t data) {reg->f.tx_buf_av = data;};
    inline uint32_t tx_buf_av()                    {return reg->f.tx_buf_av;};
    inline void     tx_state(const uint32_t data) {reg->f.tx_state = data;};
    inline uint32_t tx_state()                    {return reg->f.tx_state;};

    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    csr__status__phy_t* reg;
};

// -----------------------------------------------------
class csr__status_vp_t {
public:

    csr__status_vp_t(uint32_t* base_addr)
    {
        err = new csr__status__err_vp_t (base_addr + 0x0/4);
        phy = new csr__status__phy_vp_t (base_addr + 0x4/4);
    };

    csr__status__err_vp_t* err;
    csr__status__phy_vp_t* phy;
} ;

// -----------------------------------------------------
class csr_vp_t {
public:

    csr_vp_t(uint32_t* base_addr = (uint32_t*)0x30000000)
    {
        tx = new csr__tx_vp_t (base_addr + 0x0/4);
        rx = new csr__rx_vp_t (base_addr + 0x10/4);
        status = new csr__status_vp_t (base_addr + 0x1c/4);
    };

    csr__tx_vp_t* tx;
    csr__rx_vp_t* rx;
    csr__status_vp_t* status;
} ;


#endif
