// SPDX-FileCopyrightText: 2026 Chili.CHIPS*ba
//
// SPDX-License-Identifier: BSD-3-Clause

// ----------------------------------------------------------------------
// Auto-generated by sysrdl_cosim. *** DO NOT EDIT! ***
// Common openPCIE HAL header for both platform and co-simulation
//
// Copyright (C) 2026 Chili.CHIPS*ba
//
// ----------------------------------------------------------------------

#ifndef _CSR_BUILD_GENERATED_FILES_CSR_COSIM_H_ 
#define _CSR_BUILD_GENERATED_FILES_CSR_COSIM_H_

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "VUser.h"
#ifdef __cplusplus
}
#endif

#include "csr.h"

// Definitions for co-simulation builds
#define PCIEMAIN                VUserMain0
#define NO_DELTA_UPDATE         0

#ifndef SOC_CPU_VPNODE
#define SOC_CPU_VPNODE          0
#endif

#ifndef SOC_CPU_CLK_PERIOD_PS
#define SOC_CPU_CLK_PERIOD_PS   16000
#endif

// -----------------------------------------------------
class imem_vp_t {
public:

    imem_vp_t(uint32_t* base_addr = (uint32_t*)0x0)
    {
    };

} ;

// -----------------------------------------------------
//
class csr__tx__header0_vp_t {
public:
    csr__tx__header0_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     hdr (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t hdr () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__TX__HEADER0__HDR_bm) >> CSR__TX__HEADER0__HDR_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__tx__header1_vp_t {
public:
    csr__tx__header1_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     hdr (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t hdr () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__TX__HEADER1__HDR_bm) >> CSR__TX__HEADER1__HDR_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__tx__header2_vp_t {
public:
    csr__tx__header2_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     hdr (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t hdr () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__TX__HEADER2__HDR_bm) >> CSR__TX__HEADER2__HDR_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__tx__data_vp_t {
public:
    csr__tx__data_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     payload (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t payload () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__TX__DATA__PAYLOAD_bm) >> CSR__TX__DATA__PAYLOAD_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
class csr__tx_vp_t {
public:

    csr__tx_vp_t(uint32_t* base_addr)
    {
        header0 = new csr__tx__header0_vp_t (base_addr + 0x0/4);
        header1 = new csr__tx__header1_vp_t (base_addr + 0x4/4);
        header2 = new csr__tx__header2_vp_t (base_addr + 0x8/4);
        data = new csr__tx__data_vp_t (base_addr + 0xc/4);
    };

    csr__tx__header0_vp_t* header0;
    csr__tx__header1_vp_t* header1;
    csr__tx__header2_vp_t* header2;
    csr__tx__data_vp_t* data;
} ;

// -----------------------------------------------------
//
class csr__rx__status_vp_t {
public:
    csr__rx__status_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     cpl_status (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0x1, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t cpl_status () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__RX__STATUS__CPL_STATUS_bm) >> CSR__RX__STATUS__CPL_STATUS_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__rx__data_vp_t {
public:
    csr__rx__data_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     payload (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t payload () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__RX__DATA__PAYLOAD_bm) >> CSR__RX__DATA__PAYLOAD_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__rx__header_info_vp_t {
public:
    csr__rx__header_info_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     lower_addr (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0x1, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t lower_addr () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__RX__HEADER_INFO__LOWER_ADDR_bm) >> CSR__RX__HEADER_INFO__LOWER_ADDR_bp;
                    };

    inline void     tag (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 8, 0x2, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t tag () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__RX__HEADER_INFO__TAG_bm) >> CSR__RX__HEADER_INFO__TAG_bp;
                    };

    inline void     requester_id (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 16, 0xc, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t requester_id () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__RX__HEADER_INFO__REQUESTER_ID_bm) >> CSR__RX__HEADER_INFO__REQUESTER_ID_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
class csr__rx_vp_t {
public:

    csr__rx_vp_t(uint32_t* base_addr)
    {
        status = new csr__rx__status_vp_t (base_addr + 0x0/4);
        data = new csr__rx__data_vp_t (base_addr + 0x4/4);
        header_info = new csr__rx__header_info_vp_t (base_addr + 0x8/4);
    };

    csr__rx__status_vp_t* status;
    csr__rx__data_vp_t* data;
    csr__rx__header_info_vp_t* header_info;
} ;

// -----------------------------------------------------
//
class csr__status__err_vp_t {
public:
    csr__status__err_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     cfg_status (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0x3, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t cfg_status () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__STATUS__ERR__CFG_STATUS_bm) >> CSR__STATUS__ERR__CFG_STATUS_bp;
                    };

    inline void     msg_err_fatal (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 16, 0x4, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t msg_err_fatal () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__STATUS__ERR__MSG_ERR_FATAL_bm) >> CSR__STATUS__ERR__MSG_ERR_FATAL_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
//
class csr__status__phy_vp_t {
public:
    csr__status__phy_vp_t (uint32_t* reg_addr = 0) : reg((uint64_t)reg_addr) {};

    inline void     full(const uint32_t data) {
                        VWrite(reg, data, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t full()                    {
                        uint32_t rdata;
                        VRead(reg, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return rdata;
                    };
    inline void     tx_buf_av (const uint32_t data) {
                        uint32_t wdata = (uint32_t)(data & 0xffffffff);

                        VWriteBE(reg + 0, wdata << 0, 0x1, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);
                    };

    inline uint32_t tx_buf_av () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__STATUS__PHY__TX_BUF_AV_bm) >> CSR__STATUS__PHY__TX_BUF_AV_bp;
                    };

    inline void     tx_state (const uint32_t data) {
                                uint32_t rdata; VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                                uint32_t tmpdata = ((uint32_t)rdata << 0) & ~CSR__STATUS__PHY__TX_STATE_bm;
                                tmpdata |= ((data << CSR__STATUS__PHY__TX_STATE_bp) & CSR__STATUS__PHY__TX_STATE_bm) >> 0;
                                uint32_t wdata = (uint32_t)(tmpdata & 0xffffffff);

                                VWriteBE(reg + 0, wdata, 0xf, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                                VTick(rand() % 33, SOC_CPU_VPNODE);
                      };

    inline uint32_t tx_state () {
                        uint32_t rdata;

                        VRead(reg + 0, &rdata, NO_DELTA_UPDATE, SOC_CPU_VPNODE);
                        VTick(rand() % 33, SOC_CPU_VPNODE);

                        return (((uint32_t)rdata << 0) & CSR__STATUS__PHY__TX_STATE_bm) >> CSR__STATUS__PHY__TX_STATE_bp;
                    };


    inline uint32_t* get_addr() {return (uint32_t*)((uint64_t)reg);}

private:
    uint32_t reg;
};

// -----------------------------------------------------
class csr__status_vp_t {
public:

    csr__status_vp_t(uint32_t* base_addr)
    {
        err = new csr__status__err_vp_t (base_addr + 0x0/4);
        phy = new csr__status__phy_vp_t (base_addr + 0x4/4);
    };

    csr__status__err_vp_t* err;
    csr__status__phy_vp_t* phy;
} ;

// -----------------------------------------------------
class csr_vp_t {
public:

    csr_vp_t(uint32_t* base_addr = (uint32_t*)0x30000000)
    {
        tx = new csr__tx_vp_t (base_addr + 0x0/4);
        rx = new csr__rx_vp_t (base_addr + 0x10/4);
        status = new csr__status_vp_t (base_addr + 0x1c/4);
    };

    csr__tx_vp_t* tx;
    csr__rx_vp_t* rx;
    csr__status_vp_t* status;
} ;


#endif
