// SPDX-FileCopyrightText: 2026 Chili.CHIPS*ba
//
// SPDX-License-Identifier: BSD-3-Clause

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 6;
    localparam CSR_SIZE = 'h24;

    typedef struct {
        logic [2:0] next;
        logic we;
    } csr__rx__status__cpl_status__in_t;

    typedef struct {
        csr__rx__status__cpl_status__in_t cpl_status;
    } csr__rx__status__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } csr__rx__data__payload__in_t;

    typedef struct {
        csr__rx__data__payload__in_t payload;
    } csr__rx__data__in_t;

    typedef struct {
        logic [6:0] next;
        logic we;
    } csr__rx__header_info__lower_addr__in_t;

    typedef struct {
        logic [7:0] next;
        logic we;
    } csr__rx__header_info__tag__in_t;

    typedef struct {
        logic [15:0] next;
        logic we;
    } csr__rx__header_info__requester_id__in_t;

    typedef struct {
        csr__rx__header_info__lower_addr__in_t lower_addr;
        csr__rx__header_info__tag__in_t tag;
        csr__rx__header_info__requester_id__in_t requester_id;
    } csr__rx__header_info__in_t;

    typedef struct {
        csr__rx__status__in_t status;
        csr__rx__data__in_t data;
        csr__rx__header_info__in_t header_info;
    } csr__rx__in_t;

    typedef struct {
        logic [15:0] next;
    } csr__status__err__cfg_status__in_t;

    typedef struct {
        logic next;
    } csr__status__err__msg_err_fatal__in_t;

    typedef struct {
        csr__status__err__cfg_status__in_t cfg_status;
        csr__status__err__msg_err_fatal__in_t msg_err_fatal;
    } csr__status__err__in_t;

    typedef struct {
        logic [5:0] next;
    } csr__status__phy__tx_buf_av__in_t;

    typedef struct {
        logic [1:0] next;
    } csr__status__phy__tx_state__in_t;

    typedef struct {
        csr__status__phy__tx_buf_av__in_t tx_buf_av;
        csr__status__phy__tx_state__in_t tx_state;
    } csr__status__phy__in_t;

    typedef struct {
        csr__status__err__in_t err;
        csr__status__phy__in_t phy;
    } csr__status__in_t;

    typedef struct {
        csr__rx__in_t rx;
        csr__status__in_t status;
    } csr__in_t;

    typedef struct {
        logic [31:0] value;
    } csr__tx__header0__hdr__out_t;

    typedef struct {
        csr__tx__header0__hdr__out_t hdr;
    } csr__tx__header0__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__tx__header1__hdr__out_t;

    typedef struct {
        csr__tx__header1__hdr__out_t hdr;
    } csr__tx__header1__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__tx__header2__hdr__out_t;

    typedef struct {
        csr__tx__header2__hdr__out_t hdr;
    } csr__tx__header2__out_t;

    typedef struct {
        logic [31:0] value;
        logic swmod;
    } csr__tx__data__payload__out_t;

    typedef struct {
        csr__tx__data__payload__out_t payload;
    } csr__tx__data__out_t;

    typedef struct {
        csr__tx__header0__out_t header0;
        csr__tx__header1__out_t header1;
        csr__tx__header2__out_t header2;
        csr__tx__data__out_t data;
    } csr__tx__out_t;

    typedef struct {
        csr__tx__out_t tx;
    } csr__out_t;
endpackage
